"use client";
import {FormEvent,useEffect,useState} from "react";
import {api} from "@/lib/api";
import {usePreferences} from "./app-preferences";
type KB={id:string;name:string};type Source={id:string;title:string;source_type:string;status:string;enabled_in_retrieval:boolean};
export function SourcesPanel(){
 const{t,errorText}=usePreferences();const[bases,setBases]=useState<KB[]>([]);const[kb,setKb]=useState("");const[items,setItems]=useState<Source[]>([]);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);
 async function refresh(id:string){setItems(await api<Source[]>(`/knowledge-bases/${id}/sources`));setLoading(false)}
 useEffect(()=>{api<KB[]>("/knowledge-bases").then(rows=>{setBases(rows);setKb(rows[0]?.id||"");if(!rows.length)setLoading(false)}).catch(error=>{setError(errorText(error));setLoading(false)})},[errorText]);
 useEffect(()=>{if(kb)void refresh(kb).catch(error=>{setError(errorText(error));setLoading(false)})},[kb,errorText]);
 async function perform(action:()=>Promise<unknown>){setBusy(true);setError("");setNotice("");try{await action();await refresh(kb);setNotice(t.saved)}catch(error){setError(errorText(error))}finally{setBusy(false)}}
 const statusLabel=(status:string)=>({ready:t.ready,approved:t.approved,processing:t.processing,archived:t.archived,failed:t.failed}[status]||status);const typeLabel=(type:string)=>({upload:t.uploadSource,website_snapshot:t.websiteSource,github_playbook:t.playbookSource}[type]||type);
 function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;void perform(async()=>{await api(`/knowledge-bases/${kb}/sources/upload`,{method:"POST",body:new FormData(form)});form.reset()})}
 function site(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);void perform(async()=>{await api(`/knowledge-bases/${kb}/sources/site`,{method:"POST",body:JSON.stringify({url:data.get("url")})});form.reset()})}
 if(loading)return <p role="status">{t.loading}</p>;
 return <div className="stack"><h1>📄 {t.sources}</h1>{error&&<p role="alert">{error} <button onClick={()=>kb&&void refresh(kb)}>{t.retry}</button></p>}{notice&&<p role="status">{notice}</p>}<section className="panel stack">{bases.length?<><label>{t.chooseBase}<select value={kb} onChange={e=>setKb(e.target.value)}>{bases.map(base=><option value={base.id} key={base.id}>{base.name}</option>)}</select></label><form className="row wrap" onSubmit={upload}><input aria-label={t.upload} type="file" name="file" accept=".txt,.md,.pdf" required/><button disabled={busy||!kb} className="primary">{t.upload}</button></form><form className="row wrap" onSubmit={site}><input aria-label="URL" name="url" type="url" placeholder="https://…" required/><button disabled={busy||!kb} className="primary">{t.addWebsite}</button></form>{items.length?items.map(source=><article className="panel row wrap" key={source.id}><strong>{source.title}</strong><span className="muted">{typeLabel(source.source_type)} · {statusLabel(source.status)}</span>{source.status==="ready"&&<button disabled={busy} onClick={()=>void perform(()=>api(`/knowledge-bases/${kb}/sources/${source.id}/approve`,{method:"POST"}))}>{t.approve}</button>}{source.status==="approved"&&<button disabled={busy} onClick={()=>void perform(()=>api(`/knowledge-bases/${kb}/sources/${source.id}/retrieval?enabled=${!source.enabled_in_retrieval}`,{method:"POST"}))}>{source.enabled_in_retrieval?t.disable:t.enable}</button>}<button disabled={busy} onClick={()=>void perform(()=>api(`/knowledge-bases/${kb}/sources/${source.id}/archive`,{method:"POST"}))}>{t.archive}</button><button className="danger" disabled={busy} onClick={()=>window.confirm(t.confirmDelete)&&void perform(()=>api(`/knowledge-bases/${kb}/sources/${source.id}`,{method:"DELETE"}))}>{t.remove}</button></article>):<p className="muted">{t.empty}</p>}</>:<div className="empty-action"><p>{t.createBaseHint}</p><a href="/manage" className="button-link primary">＋ {t.newBase}</a></div>}</section></div>
}
